using Gurung.BulkOperations.SqlServer.Tests.Context;
using Gurung.BulkOperations.SqlServer.Tests.Entity;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Testcontainers.MsSql;
using Xunit;

namespace Gurung.BulkOperations.SqlServer.Tests.SqlServer
{
    /// <summary>
    /// Integration tests for SQL Server bulk insert operations with IDENTITY column handling.
    /// Tests both IDENTITY_INSERT ON (KeepIdentity = true) and OFF (KeepIdentity = false) scenarios.
    /// </summary>
    public class SqlServerBulkInsertIdentityTests : IAsyncLifetime
    {
        private readonly MsSqlContainer _sqlContainer;
        private AppDbContext _context;

        public SqlServerBulkInsertIdentityTests()
        {
            _sqlContainer = new MsSqlBuilder()
                .WithPassword("yourStrong(!)Password")
                .WithImage("mcr.microsoft.com/mssql/server:2022-latest")
                .Build();
        }

        public async Task DisposeAsync()
        {
            await _sqlContainer.StopAsync();
            await _sqlContainer.DisposeAsync();
        }

        public async Task InitializeAsync()
        {
            await _sqlContainer.StartAsync();

            var options = new DbContextOptionsBuilder<AppDbContext>()
                .UseSqlServer(_sqlContainer.GetConnectionString())
                .Options;

            _context = new AppDbContext(options);
            await _context.Database.EnsureCreatedAsync();
        }

        #region IDENTITY_INSERT OFF (KeepIdentity = false) - Default Behavior

        [Fact]
        public async Task BulkInsert_WithAutoGeneratedIds_ShouldInsertSuccessfully()
        {
            // Arrange - Create users WITHOUT specifying IDs (Id = 0 or default)
            var users = new List<UserEntity>
            {
                new UserEntity { Name = "John Doe", Email = "john@test.com", CreatedAt = DateTime.UtcNow },
                new UserEntity { Name = "Jane Smith", Email = "jane@test.com", CreatedAt = DateTime.UtcNow },
                new UserEntity { Name = "Bob Johnson", Email = "bob@test.com", CreatedAt = DateTime.UtcNow }
            };

            var stopwatch = Stopwatch.StartNew();

            // Act - Insert with KeepIdentity = false (default) - IDENTITY_INSERT OFF
            await _context.Users.BulkInsertAsync(users, new BulkConfig { KeepIdentity = false });
            stopwatch.Stop();

            Console.WriteLine($"BulkInsert (auto ID) completed in {stopwatch.ElapsedMilliseconds} ms");

            // Assert
            var count = await _context.Users.CountAsync();
            Assert.Equal(3, count);

            // Verify IDs were auto-generated
            var insertedUsers = await _context.Users.OrderBy(u => u.Id).ToListAsync();
            Assert.True(insertedUsers[0].Id > 0, "First user should have auto-generated ID");
            Assert.True(insertedUsers[1].Id > insertedUsers[0].Id, "IDs should be sequential");
            Assert.True(insertedUsers[2].Id > insertedUsers[1].Id, "IDs should be sequential");

            // Verify data integrity
            Assert.Equal("John Doe", insertedUsers[0].Name);
            Assert.Equal("jane@test.com", insertedUsers[1].Email);
        }

        [Fact]
        public async Task BulkInsert_WithDefaultConfig_ShouldIgnoreProvidedIds()
        {
            // Arrange - Users with manually set IDs (should be ignored)
            var users = new List<UserEntity>
            {
                new UserEntity { Id = 100, Name = "User 100", Email = "user100@test.com", CreatedAt = DateTime.UtcNow },
                new UserEntity { Id = 200, Name = "User 200", Email = "user200@test.com", CreatedAt = DateTime.UtcNow },
                new UserEntity { Id = 300, Name = "User 300", Email = "user300@test.com", CreatedAt = DateTime.UtcNow }
            };

            // Act - Default behavior (KeepIdentity = false)
            await _context.Users.BulkInsertAsync(users);

            // Assert
            var insertedUsers = await _context.Users.OrderBy(u => u.Id).ToListAsync();
            
            // IDs should NOT be 100, 200, 300 - they should be auto-generated starting from 1
            Assert.NotEqual(100, insertedUsers[0].Id);
            Assert.NotEqual(200, insertedUsers[1].Id);
            Assert.NotEqual(300, insertedUsers[2].Id);
            
            // IDs should start from 1 and be sequential
            Assert.Equal(1, insertedUsers[0].Id);
            Assert.Equal(2, insertedUsers[1].Id);
            Assert.Equal(3, insertedUsers[2].Id);
        }

        [Fact]
        public async Task BulkInsert_LargeDataset_WithAutoIds_ShouldBePerformant()
        {
            // Arrange
            var users = Enumerable.Range(1, 10000).Select(i => new UserEntity
            {
                Name = $"User_{i}",
                Email = $"user{i}@test.com",
                CreatedAt = DateTime.UtcNow
            }).ToList();

            var stopwatch = Stopwatch.StartNew();

            // Act
            await _context.Users.BulkInsertAsync(users, new BulkConfig { KeepIdentity = false });
            stopwatch.Stop();

            Console.WriteLine($"Inserted 10,000 records with auto IDs in {stopwatch.ElapsedMilliseconds} ms");

            // Assert
            Assert.True(stopwatch.ElapsedMilliseconds < 5000, $"Insert took {stopwatch.ElapsedMilliseconds} ms, expected < 5000 ms");

            var count = await _context.Users.CountAsync();
            Assert.Equal(10000, count);

            // Verify sequential IDs
            var firstUser = await _context.Users.OrderBy(u => u.Id).FirstAsync();
            var lastUser = await _context.Users.OrderByDescending(u => u.Id).FirstAsync();
            
            Assert.Equal(1, firstUser.Id);
            Assert.Equal(10000, lastUser.Id);
        }

        #endregion

        #region IDENTITY_INSERT ON (KeepIdentity = true) - Explicit ID Management

        [Fact]
        public async Task BulkInsert_WithKeepIdentityTrue_ShouldPreserveProvidedIds()
        {
            // Arrange - Users with specific IDs that should be preserved
            var users = new List<UserEntity>
            {
                new UserEntity { Id = 1000, Name = "User 1000", Email = "user1000@test.com", CreatedAt = DateTime.UtcNow },
                new UserEntity { Id = 2000, Name = "User 2000", Email = "user2000@test.com", CreatedAt = DateTime.UtcNow },
                new UserEntity { Id = 3000, Name = "User 3000", Email = "user3000@test.com", CreatedAt = DateTime.UtcNow }
            };

            var stopwatch = Stopwatch.StartNew();

            // Act - Insert with KeepIdentity = true - IDENTITY_INSERT ON
            await _context.Users.BulkInsertAsync(users, new BulkConfig { KeepIdentity = true });
            stopwatch.Stop();

            Console.WriteLine($"BulkInsert (keep ID) completed in {stopwatch.ElapsedMilliseconds} ms");

            // Assert
            var count = await _context.Users.CountAsync();
            Assert.Equal(3, count);

            // Verify exact IDs were preserved
            var user1000 = await _context.Users.FirstOrDefaultAsync(u => u.Id == 1000);
            var user2000 = await _context.Users.FirstOrDefaultAsync(u => u.Id == 2000);
            var user3000 = await _context.Users.FirstOrDefaultAsync(u => u.Id == 3000);

            Assert.NotNull(user1000);
            Assert.NotNull(user2000);
            Assert.NotNull(user3000);

            Assert.Equal("User 1000", user1000.Name);
            Assert.Equal("user2000@test.com", user2000.Email);
            Assert.Equal("User 3000", user3000.Name);
        }

        [Fact]
        public async Task BulkInsert_WithKeepIdentityTrue_ShouldInsertNonSequentialIds()
        {
            // Arrange - Non-sequential IDs (gaps in sequence)
            var users = new List<UserEntity>
            {
                new UserEntity { Id = 5, Name = "User 5", Email = "user5@test.com", CreatedAt = DateTime.UtcNow },
                new UserEntity { Id = 10, Name = "User 10", Email = "user10@test.com", CreatedAt = DateTime.UtcNow },
                new UserEntity { Id = 100, Name = "User 100", Email = "user100@test.com", CreatedAt = DateTime.UtcNow },
                new UserEntity { Id = 500, Name = "User 500", Email = "user500@test.com", CreatedAt = DateTime.UtcNow }
            };

            // Act
            await _context.Users.BulkInsertAsync(users, new BulkConfig { KeepIdentity = true });

            // Assert
            var allUsers = await _context.Users.OrderBy(u => u.Id).ToListAsync();
            Assert.Equal(4, allUsers.Count);

            Assert.Equal(5, allUsers[0].Id);
            Assert.Equal(10, allUsers[1].Id);
            Assert.Equal(100, allUsers[2].Id);
            Assert.Equal(500, allUsers[3].Id);
        }

        [Fact]
        public async Task BulkInsert_WithKeepIdentityTrue_LargeDataset_ShouldPreserveAllIds()
        {
            // Arrange - Create users with specific IDs starting from 5000
            var users = Enumerable.Range(5000, 5000).Select(i => new UserEntity
            {
                Id = i,
                Name = $"User_{i}",
                Email = $"user{i}@test.com",
                CreatedAt = DateTime.UtcNow
            }).ToList();

            var stopwatch = Stopwatch.StartNew();

            // Act
            await _context.Users.BulkInsertAsync(users, new BulkConfig { KeepIdentity = true });
            stopwatch.Stop();

            Console.WriteLine($"Inserted 5,000 records with explicit IDs in {stopwatch.ElapsedMilliseconds} ms");

            // Assert
            Assert.True(stopwatch.ElapsedMilliseconds < 5000, $"Insert took {stopwatch.ElapsedMilliseconds} ms");

            var count = await _context.Users.CountAsync();
            Assert.Equal(5000, count);

            // Verify IDs are preserved
            var firstUser = await _context.Users.OrderBy(u => u.Id).FirstAsync();
            var lastUser = await _context.Users.OrderByDescending(u => u.Id).FirstAsync();

            Assert.Equal(5000, firstUser.Id);
            Assert.Equal(9999, lastUser.Id);

            // Spot check a few IDs
            var user7500 = await _context.Users.FindAsync(7500);
            Assert.NotNull(user7500);
            Assert.Equal("User_7500", user7500.Name);
        }

        [Fact]
        public async Task BulkInsert_WithKeepIdentityTrue_ShouldHandleDuplicateIdScenario()
        {
            // Arrange - First insert with ID = 1
            var firstUser = new List<UserEntity>
            {
                new UserEntity { Id = 1, Name = "First User", Email = "first@test.com", CreatedAt = DateTime.UtcNow }
            };

            await _context.Users.BulkInsertAsync(firstUser, new BulkConfig { KeepIdentity = true });

            // Try to insert another user with the same ID
            var duplicateUser = new List<UserEntity>
            {
                new UserEntity { Id = 1, Name = "Duplicate User", Email = "duplicate@test.com", CreatedAt = DateTime.UtcNow }
            };

            // Act & Assert - Should throw exception for duplicate primary key
            await Assert.ThrowsAnyAsync<Exception>(async () =>
            {
                await _context.Users.BulkInsertAsync(duplicateUser, new BulkConfig { KeepIdentity = true });
            });

            // Verify only the first user exists
            var count = await _context.Users.CountAsync();
            Assert.Equal(1, count);

            var user = await _context.Users.FindAsync(1);
            Assert.Equal("First User", user.Name);
        }

        #endregion

        #region Mixed Scenarios and Edge Cases

        [Fact]
        public async Task BulkInsert_MultipleOperations_WithDifferentKeepIdentitySettings()
        {
            // Arrange & Act - Phase 1: Insert with auto IDs
            var autoIdUsers = new List<UserEntity>
            {
                new UserEntity { Name = "Auto 1", Email = "auto1@test.com", CreatedAt = DateTime.UtcNow },
                new UserEntity { Name = "Auto 2", Email = "auto2@test.com", CreatedAt = DateTime.UtcNow }
            };

            await _context.Users.BulkInsertAsync(autoIdUsers, new BulkConfig { KeepIdentity = false });

            // Phase 2: Insert with specific IDs
            var explicitIdUsers = new List<UserEntity>
            {
                new UserEntity { Id = 1000, Name = "Explicit 1000", Email = "explicit1000@test.com", CreatedAt = DateTime.UtcNow },
                new UserEntity { Id = 2000, Name = "Explicit 2000", Email = "explicit2000@test.com", CreatedAt = DateTime.UtcNow }
            };

            await _context.Users.BulkInsertAsync(explicitIdUsers, new BulkConfig { KeepIdentity = true });

            // Phase 3: Insert more auto IDs (should continue from last auto-generated ID)
            var moreAutoIdUsers = new List<UserEntity>
            {
                new UserEntity { Name = "Auto 3", Email = "auto3@test.com", CreatedAt = DateTime.UtcNow }
            };

            await _context.Users.BulkInsertAsync(moreAutoIdUsers, new BulkConfig { KeepIdentity = false });

            // Assert
            var allUsers = await _context.Users.OrderBy(u => u.Id).ToListAsync();
            Assert.Equal(5, allUsers.Count);

            // Verify auto-generated IDs (should be 1, 2, 3)
            var autoUsers = allUsers.Where(u => u.Name.StartsWith("Auto")).OrderBy(u => u.Id).ToList();
            Assert.Equal(3, autoUsers.Count);

            // Verify explicit IDs (1000, 2000)
            var explicitUsers = allUsers.Where(u => u.Name.StartsWith("Explicit")).ToList();
            Assert.Equal(2, explicitUsers.Count);
            Assert.Contains(explicitUsers, u => u.Id == 1000);
            Assert.Contains(explicitUsers, u => u.Id == 2000);
        }

        [Fact]
        public async Task BulkInsert_EmptyList_ShouldNotThrowException()
        {
            // Arrange
            var emptyList = new List<UserEntity>();

            // Act & Assert - Should not throw
            await _context.Users.BulkInsertAsync(emptyList, new BulkConfig { KeepIdentity = false });
            await _context.Users.BulkInsertAsync(emptyList, new BulkConfig { KeepIdentity = true });

            var count = await _context.Users.CountAsync();
            Assert.Equal(0, count);
        }

        [Fact]
        public async Task BulkInsert_SingleRecord_WithKeepIdentityFalse()
        {
            // Arrange
            var singleUser = new List<UserEntity>
            {
                new UserEntity { Name = "Single User", Email = "single@test.com", CreatedAt = DateTime.UtcNow }
            };

            // Act
            await _context.Users.BulkInsertAsync(singleUser, new BulkConfig { KeepIdentity = false });

            // Assert
            var user = await _context.Users.FirstAsync();
            Assert.Equal(1, user.Id);
            Assert.Equal("Single User", user.Name);
        }

        [Fact]
        public async Task BulkInsert_SingleRecord_WithKeepIdentityTrue()
        {
            // Arrange
            var singleUser = new List<UserEntity>
            {
                new UserEntity { Id = 9999, Name = "Single User 9999", Email = "single9999@test.com", CreatedAt = DateTime.UtcNow }
            };

            // Act
            await _context.Users.BulkInsertAsync(singleUser, new BulkConfig { KeepIdentity = true });

            // Assert
            var user = await _context.Users.FirstAsync();
            Assert.Equal(9999, user.Id);
            Assert.Equal("Single User 9999", user.Name);
        }

        [Fact]
        public async Task BulkInsert_WithSpecialCharacters_ShouldPreserveData()
        {
            // Arrange
            var users = new List<UserEntity>
            {
                new UserEntity { Name = "O'Brien", Email = "o'brien@test.com", CreatedAt = DateTime.UtcNow },
                new UserEntity { Name = "José García", Email = "josé@test.com", CreatedAt = DateTime.UtcNow },
                new UserEntity { Name = "Test \"Quote\"", Email = "quote@test.com", CreatedAt = DateTime.UtcNow }
            };

            // Act
            await _context.Users.BulkInsertAsync(users, new BulkConfig { KeepIdentity = false });

            // Assert
            var count = await _context.Users.CountAsync();
            Assert.Equal(3, count);

            var obrien = await _context.Users.FirstOrDefaultAsync(u => u.Name == "O'Brien");
            Assert.NotNull(obrien);

            var jose = await _context.Users.FirstOrDefaultAsync(u => u.Name == "José García");
            Assert.NotNull(jose);
        }

        [Fact]
        public async Task BulkInsert_PerformanceComparison_KeepIdentityTrueVsFalse()
        {
            // Arrange
            var recordCount = 5000;
            var usersAutoId = Enumerable.Range(1, recordCount).Select(i => new UserEntity
            {
                Name = $"AutoUser_{i}",
                Email = $"auto{i}@test.com",
                CreatedAt = DateTime.UtcNow
            }).ToList();

            var usersExplicitId = Enumerable.Range(10000, recordCount).Select(i => new UserEntity
            {
                Id = i,
                Name = $"ExplicitUser_{i}",
                Email = $"explicit{i}@test.com",
                CreatedAt = DateTime.UtcNow
            }).ToList();

            // Act - Auto ID
            var stopwatch1 = Stopwatch.StartNew();
            await _context.Users.BulkInsertAsync(usersAutoId, new BulkConfig { KeepIdentity = false });
            stopwatch1.Stop();

            // Act - Explicit ID
            var stopwatch2 = Stopwatch.StartNew();
            await _context.Users.BulkInsertAsync(usersExplicitId, new BulkConfig { KeepIdentity = true });
            stopwatch2.Stop();

            Console.WriteLine($"\n=== PERFORMANCE COMPARISON ===");
            Console.WriteLine($"KeepIdentity = false (IDENTITY_INSERT OFF): {stopwatch1.ElapsedMilliseconds} ms for {recordCount:N0} records");
            Console.WriteLine($"KeepIdentity = true  (IDENTITY_INSERT ON):  {stopwatch2.ElapsedMilliseconds} ms for {recordCount:N0} records");
            Console.WriteLine($"Difference: {Math.Abs(stopwatch1.ElapsedMilliseconds - stopwatch2.ElapsedMilliseconds)} ms");

            // Assert
            var totalCount = await _context.Users.CountAsync();
            Assert.Equal(recordCount * 2, totalCount);

            // Both should be reasonably fast
            Assert.True(stopwatch1.ElapsedMilliseconds < 5000);
            Assert.True(stopwatch2.ElapsedMilliseconds < 5000);
        }

        #endregion
    }
}
