using Gurung.BulkOperations.Core.Context;
using Gurung.BulkOperations.Core.Entity;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using Testcontainers.PostgreSql;
using Xunit;
using Xunit.Abstractions;
using Gurung.BulkOperations;

namespace Gurung.BulkOperation.PostgreSql.Tests.PostgreSql
{
    public class PostgreSqlBulkOperationsTavernTests : IAsyncLifetime
    {
        private readonly PostgreSqlContainer _pgContainer;
        private AppDbContext _context;
        private readonly ITestOutputHelper _output;

        public PostgreSqlBulkOperationsTavernTests(ITestOutputHelper output)
        {
            _output = output;
            _pgContainer = new PostgreSqlBuilder()
                .WithImage("postgres:16-alpine")
                .WithUsername("postgres")
                .WithPassword("postgres")
                .WithDatabase("testdb")
                .WithPortBinding(5432, true)
                .Build();
        }

        public async Task InitializeAsync()
        {
            await _pgContainer.StartAsync();

            var options = new DbContextOptionsBuilder<AppDbContext>()
                .UseNpgsql(_pgContainer.GetConnectionString())
                .Options;

            _context = new AppDbContext(options);
            await _context.Database.EnsureCreatedAsync();
        }

        public async Task DisposeAsync()
        {
            await _context.DisposeAsync();
            await _pgContainer.StopAsync();
            await _pgContainer.DisposeAsync();
        }

        [Fact]
        public async Task BulkInsertAsync_WithAutoGeneratedIds_ShouldInsertTavernsSuccessfully()
        {
            // Arrange
            var taverns = new List<Tavern>
            {
                CreateTavern("user1", "The Prancing Pony", "Bree"),
                CreateTavern("user2", "The Green Dragon", "Hobbiton"),
                CreateTavern("user3", "The Golden Perch", "Bywater")
            };

            var stopwatch = Stopwatch.StartNew();

            // Act
            await _context.BulkInsertAsync(taverns);
            stopwatch.Stop();

            // Assert
            var insertedTaverns = await _context.Taverns.ToListAsync();
            Assert.Equal(3, insertedTaverns.Count);
            Assert.All(insertedTaverns, t => Assert.True(t.Id > 0));
            Assert.Contains(insertedTaverns, t => t.TavernName == "The Prancing Pony");
            Assert.Contains(insertedTaverns, t => t.City == "Hobbiton");

            _output.WriteLine($"BulkInsert of 3 taverns took: {stopwatch.ElapsedMilliseconds}ms");
        }

        [Fact]
        public async Task BulkInsertAsync_WithLargeDataset_ShouldInsertAllTavernsSuccessfully()
        {
            // Arrange
            var taverns = Enumerable.Range(1, 1000)
                .Select(i => CreateTavern($"user{i}", $"Tavern {i}", $"City {i}"))
                .ToList();

            var stopwatch = Stopwatch.StartNew();

            // Act
            await _context.BulkInsertAsync(taverns);
            stopwatch.Stop();

            // Assert
            var count = await _context.Taverns.CountAsync();
            Assert.Equal(1000, count);

            _output.WriteLine($"BulkInsert of 1000 taverns took: {stopwatch.ElapsedMilliseconds}ms");
        }

        [Fact]
        public async Task BulkInsertAsync_WithExplicitIds_ShouldInsertTavernsWithSpecifiedIds()
        {
            // Arrange
            var taverns = new List<Tavern>
            {
                CreateTavern("user1", "The Prancing Pony", "Bree", id: 100),
                CreateTavern("user2", "The Green Dragon", "Hobbiton", id: 200),
                CreateTavern("user3", "The Golden Perch", "Bywater", id: 300)
            };

            var stopwatch = Stopwatch.StartNew();

            // Act
            await _context.BulkInsertAsync(taverns, new BulkConfig { KeepIdentity = true });
            stopwatch.Stop();

            // Assert
            var insertedTaverns = await _context.Taverns.OrderBy(t => t.Id).ToListAsync();
            Assert.Equal(3, insertedTaverns.Count);
            Assert.Equal(100, insertedTaverns[0].Id);
            Assert.Equal(200, insertedTaverns[1].Id);
            Assert.Equal(300, insertedTaverns[2].Id);

            _output.WriteLine($"BulkInsert with explicit IDs took: {stopwatch.ElapsedMilliseconds}ms");
        }

        [Fact]
        public async Task BulkUpdateAsync_WithSmallDataset_ShouldUpdateTavernsSuccessfully()
        {
            // Arrange - Insert initial data
            var taverns = new List<Tavern>
            {
                CreateTavern("user1", "The Prancing Pony", "Bree"),
                CreateTavern("user2", "The Green Dragon", "Hobbiton"),
                CreateTavern("user3", "The Golden Perch", "Bywater")
            };
            await _context.BulkInsertAsync(taverns);

            // Get inserted records
            var insertedTaverns = await _context.Taverns.ToListAsync();
            
            // Modify data
            foreach (var tavern in insertedTaverns)
            {
                tavern.TavernName = $"{tavern.TavernName} (Updated)";
                tavern.City = $"{tavern.City} - Updated";
                tavern.MaxTable = 100;
                tavern.IsActive = false;
            }

            var stopwatch = Stopwatch.StartNew();

            // Act
            await _context.BulkUpDateAsync(insertedTaverns);
            stopwatch.Stop();

            // Assert
            var updatedTaverns = await _context.Taverns.ToListAsync();
            Assert.Equal(3, updatedTaverns.Count);
            Assert.All(updatedTaverns, t => Assert.Contains("(Updated)", t.TavernName));
            Assert.All(updatedTaverns, t => Assert.Contains("Updated", t.City));
            Assert.All(updatedTaverns, t => Assert.Equal(100, t.MaxTable));
            Assert.All(updatedTaverns, t => Assert.False(t.IsActive));

            _output.WriteLine($"BulkUpdate of 3 taverns took: {stopwatch.ElapsedMilliseconds}ms");
        }

        [Fact]
        public async Task BulkUpdateAsync_WithLargeDataset_ShouldUpdateAllTavernsSuccessfully()
        {
            // Arrange - Insert initial data
            var taverns = Enumerable.Range(1, 500)
                .Select(i => CreateTavern($"user{i}", $"Tavern {i}", $"City {i}"))
                .ToList();
            await _context.BulkInsertAsync(taverns);

            // Get inserted records
            var insertedTaverns = await _context.Taverns.ToListAsync();
            
            // Modify all records
            foreach (var tavern in insertedTaverns)
            {
                tavern.MaxTable = 200;
                tavern.AverageTeams = 25;
                tavern.TvVersion = true;
            }

            var stopwatch = Stopwatch.StartNew();

            // Act
            await _context.BulkUpDateAsync(insertedTaverns);
            stopwatch.Stop();

            // Assert
            var updatedTaverns = await _context.Taverns.ToListAsync();
            Assert.Equal(500, updatedTaverns.Count);
            Assert.All(updatedTaverns, t => Assert.Equal(200, t.MaxTable));
            Assert.All(updatedTaverns, t => Assert.Equal(25, t.AverageTeams));
            Assert.All(updatedTaverns, t => Assert.True(t.TvVersion));

            _output.WriteLine($"BulkUpdate of 500 taverns took: {stopwatch.ElapsedMilliseconds}ms");
        }

        [Fact]
        public async Task BulkInsertOrUpdateAsync_WithMixedData_ShouldInsertNewAndUpdateExisting()
        {
            // Arrange - Insert initial data
            var existingTaverns = new List<Tavern>
            {
                CreateTavern("user1", "The Prancing Pony", "Bree"),
                CreateTavern("user2", "The Green Dragon", "Hobbiton")
            };
            await _context.BulkInsertAsync(existingTaverns);

            var insertedTaverns = await _context.Taverns.ToListAsync();
            
            // Modify existing and add new
            insertedTaverns[0].MaxTable = 150;
            insertedTaverns[0].TavernName = "The Prancing Pony (Renovated)";
            
            var mixedData = insertedTaverns.Concat(new[]
            {
                CreateTavern("user3", "The Golden Perch", "Bywater"),
                CreateTavern("user4", "The Ivy Bush", "Hobbiton")
            }).ToList();

            var stopwatch = Stopwatch.StartNew();

            // Act
            await _context.BulkInsertOrUpDateAsync(mixedData);
            stopwatch.Stop();

            // Assert
            var allTaverns = await _context.Taverns.OrderBy(t => t.Id).ToListAsync();
            Assert.Equal(4, allTaverns.Count);
            
            var updated = allTaverns.First(t => t.Id == insertedTaverns[0].Id);
            Assert.Equal("The Prancing Pony (Renovated)", updated.TavernName);
            Assert.Equal(150, updated.MaxTable);
            
            Assert.Contains(allTaverns, t => t.TavernName == "The Golden Perch");
            Assert.Contains(allTaverns, t => t.TavernName == "The Ivy Bush");

            _output.WriteLine($"BulkInsertOrUpdate of 4 taverns (2 updates, 2 inserts) took: {stopwatch.ElapsedMilliseconds}ms");
        }

        [Fact]
        public async Task BulkInsertOrUpdateAsync_WithLargeDataset_ShouldHandleMixedOperationsEfficiently()
        {
            // Arrange - Insert 500 initial records
            var initialTaverns = Enumerable.Range(1, 500)
                .Select(i => CreateTavern($"user{i}", $"Tavern {i}", $"City {i}"))
                .ToList();
            await _context.BulkInsertAsync(initialTaverns);

            var existingTaverns = await _context.Taverns.Take(300).ToListAsync();
            
            // Modify 300 existing records
            foreach (var tavern in existingTaverns)
            {
                tavern.MaxTable = 250;
                tavern.AverageTeams = 30;
            }

            // Add 200 new records
            var newTaverns = Enumerable.Range(501, 200)
                .Select(i => CreateTavern($"user{i}", $"New Tavern {i}", $"New City {i}"))
                .ToList();

            var mixedData = existingTaverns.Concat(newTaverns).ToList();

            var stopwatch = Stopwatch.StartNew();

            // Act
            await _context.BulkInsertOrUpDateAsync(mixedData);
            stopwatch.Stop();

            // Assert
            var totalCount = await _context.Taverns.CountAsync();
            Assert.Equal(700, totalCount); // 500 initial + 200 new

            var updatedCount = await _context.Taverns.CountAsync(t => t.MaxTable == 250);
            Assert.Equal(300, updatedCount);

            _output.WriteLine($"BulkInsertOrUpdate of 500 taverns (300 updates, 200 inserts) took: {stopwatch.ElapsedMilliseconds}ms");
        }

        [Fact]
        public async Task BulkOperations_ShouldHandleAllColumnAttributes()
        {
            // Arrange - Test all column types with [Column] attributes
            var tavern = CreateTavern("testuser", "Test Tavern", "Test City");
            
            // Set all properties to ensure column mapping works for all 66 columns
            tavern.OwnerName = "John Doe";
            tavern.CountryId = 1;
            tavern.Gender = "Male";
            tavern.StreetAddress = "123 Main Street";
            tavern.StateId = 1;
            tavern.ZipCode = "12345";
            tavern.LocationId = 100;
            tavern.County = "Test County";
            tavern.Phone = "+1234567890";
            tavern.Fax = "+0987654321";
            tavern.WebsiteUrl = "https://test-tavern.com";
            tavern.FirstName = "John";
            tavern.LastName = "Doe";
            tavern.CellPhone = "+1122334455";
            tavern.BigBrainFirstName = "Jane";
            tavern.BigBrainLastName = "Smith";
            tavern.BigBrainEmail = "jane@test.com";
            tavern.BigBrainCell = "+9988776655";
            tavern.MaxTable = 50;
            tavern.FirstNight = "Monday";
            tavern.FirstNightTime1 = "18:00";
            tavern.FirstNightTime2 = "20:00";
            tavern.SecondNight = "Wednesday";
            tavern.SecondNightTime1 = "18:30";
            tavern.SecondNightTime2 = "20:30";
            tavern.CheckInTime = "17:00";
            tavern.RegistrationCloses = "19:00";
            tavern.RegistrationOpens = "16:00";
            tavern.MaxNumberOfTeams = 20;
            tavern.IsActive = true;
            tavern.TimeZone = "EST";
            tavern.Activity = DateTime.Now;
            tavern.NumberOfTimeUpdate = 5;
            tavern.OwnerId = 123;
            tavern.Notes = "This is a test tavern with all properties";
            tavern.AverageTeams = 15;
            tavern.BonusQuestions = 3;
            tavern.BirthDate = new DateTime(1980, 1, 1);
            tavern.PlayersPerTable = 6;
            tavern.BigBrainFirstName2 = "Bob";
            tavern.BigBrainEmail2 = "bob@test.com";
            tavern.BigBrainLastName2 = "Johnson";
            tavern.BigBrainCell2 = "+5544332211";
            tavern.WeeklyFirstPrize = "$100 Gift Card";
            tavern.WeeklySecondPrize = "$50 Gift Card";
            tavern.WeeklyThirdPrize = "$25 Gift Card";
            tavern.WeeklySpecials = "Happy Hour Specials";
            tavern.TvVersion = true;
            tavern.ShippingAddress = "456 Shipping St";
            tavern.ShippingCity = "Ship City";
            tavern.ShippingStateId = 2;
            tavern.ShippingZip = "54321";
            tavern.AutoGameMode = 1;
            tavern.FoodSpecial = "Pizza and Wings";
            tavern.DrinkSpecial = "2-for-1 Beers";
            tavern.ChkOk = true;

            // Act
            await _context.BulkInsertAsync(new[] { tavern });

            // Assert
            var inserted = await _context.Taverns.FirstAsync();
            Assert.Equal("testuser", inserted.UserId);
            Assert.Equal("Test Tavern", inserted.TavernName);
            Assert.Equal("Test City", inserted.City);
            Assert.Equal("John Doe", inserted.OwnerName);
            Assert.Equal(1, inserted.CountryId);
            Assert.Equal("Male", inserted.Gender);
            Assert.Equal("123 Main Street", inserted.StreetAddress);
            Assert.Equal(1, inserted.StateId);
            Assert.Equal("12345", inserted.ZipCode);
            Assert.Equal(100, inserted.LocationId);
            Assert.Equal("Test County", inserted.County);
            Assert.Equal("+1234567890", inserted.Phone);
            Assert.Equal("+0987654321", inserted.Fax);
            Assert.Equal("https://test-tavern.com", inserted.WebsiteUrl);
            Assert.Equal("John", inserted.FirstName);
            Assert.Equal("Doe", inserted.LastName);
            Assert.Equal(50, inserted.MaxTable);
            Assert.Equal("Monday", inserted.FirstNight);
            Assert.Equal(20, inserted.MaxNumberOfTeams);
            Assert.True(inserted.IsActive);
            Assert.Equal("EST", inserted.TimeZone);
            Assert.Equal(123, inserted.OwnerId);
            Assert.Equal(15, inserted.AverageTeams);
            Assert.Equal(3, inserted.BonusQuestions);
            Assert.True(inserted.TvVersion);
            Assert.True(inserted.ChkOk);

            _output.WriteLine("All 66 column attributes handled correctly");
        }

        [Fact]
        public async Task BulkOperations_ShouldHandleNullableColumns()
        {
            // Arrange - Test nullable columns
            var tavern = new Tavern
            {
                UserId = "minimaluser",
                UserName = "minimaluser",
                Password = "password123",
                Email = "minimal@test.com",
                CountryId = 1,
                StateId = 1,
                LocationId = 1,
                MaxNumberOfTeams = 10,
                IsActive = true,
                Activity = DateTime.Now,
                OwnerId = 1,
                TvVersion = false,
                AutoGameMode = 0,
                ChkOk = false
                // All other nullable properties left as null
            };

            // Act
            await _context.BulkInsertAsync(new[] { tavern });

            // Assert
            var inserted = await _context.Taverns.FirstAsync();
            Assert.Equal("minimaluser", inserted.UserId);
            Assert.Null(inserted.OwnerName);
            Assert.Null(inserted.Gender);
            Assert.Null(inserted.TavernName);
            Assert.Null(inserted.StreetAddress);
            Assert.Null(inserted.City);
            Assert.Null(inserted.ZipCode);
            Assert.Null(inserted.Phone);
            Assert.Null(inserted.Fax);
            Assert.Null(inserted.WebsiteUrl);
            Assert.Null(inserted.MaxTable);
            Assert.Null(inserted.FirstNight);
            Assert.Null(inserted.Notes);
            Assert.Null(inserted.BirthDate);

            _output.WriteLine("Nullable columns handled correctly");
        }

        [Fact]
        public async Task BulkUpdate_ShouldUpdateOnlySpecifiedColumns()
        {
            // Arrange - Insert initial data
            var tavern = CreateTavern("user1", "Original Tavern", "Original City");
            tavern.MaxTable = 100;
            tavern.AverageTeams = 20;
            await _context.BulkInsertAsync(new[] { tavern });

            var inserted = await _context.Taverns.FirstAsync();
            
            // Modify only some columns
            inserted.TavernName = "Updated Tavern";
            inserted.MaxTable = 200;
            // AverageTeams remains unchanged

            // Act
            await _context.BulkUpDateAsync(new[] { inserted });

            // Assert
            var updated = await _context.Taverns.FirstAsync();
            Assert.Equal("Updated Tavern", updated.TavernName);
            Assert.Equal(200, updated.MaxTable);
            Assert.Equal(20, updated.AverageTeams); // Should remain unchanged
            Assert.Equal("Original City", updated.City); // Should remain unchanged

            _output.WriteLine("Partial update completed successfully");
        }

        [Fact]
        public async Task BulkInsertOrUpdate_WithComplexScenario_ShouldHandleAllOperations()
        {
            // Arrange - Create complex scenario with different states
            var initialTaverns = new List<Tavern>
            {
                CreateTavern("user1", "Tavern A", "City A", id: 1),
                CreateTavern("user2", "Tavern B", "City B", id: 2),
                CreateTavern("user3", "Tavern C", "City C", id: 3)
            };
            await _context.BulkInsertAsync(initialTaverns, new BulkConfig { KeepIdentity = true });

            // Prepare mixed data: update existing, insert new
            var existingA = await _context.Taverns.FirstAsync(t => t.Id == 1);
            existingA.TavernName = "Tavern A (Updated)";
            existingA.City = "City A Updated";
            existingA.MaxTable = 150;
            
            var existingB = await _context.Taverns.FirstAsync(t => t.Id == 2);
            existingB.TavernName = "Tavern B (Updated)";
            existingB.City = "City B Updated";
            existingB.MaxTable = 200;

            var mixedData = new List<Tavern>
            {
                existingA,
                existingB,
                CreateTavern("user4", "Tavern D", "City D"), // New
                CreateTavern("user5", "Tavern E", "City E")  // New
            };

            var stopwatch = Stopwatch.StartNew();

            // Act
            await _context.BulkInsertOrUpDateAsync(mixedData);
            stopwatch.Stop();

            // Assert
            var allTaverns = await _context.Taverns.OrderBy(t => t.Id).ToListAsync();
            Assert.Equal(5, allTaverns.Count);

            // Verify updates
            var tavernA = allTaverns.First(t => t.Id == 1);
            Assert.Equal("Tavern A (Updated)", tavernA.TavernName);
            Assert.Equal(150, tavernA.MaxTable);

            var tavernB = allTaverns.First(t => t.Id == 2);
            Assert.Equal("Tavern B (Updated)", tavernB.TavernName);
            Assert.Equal(200, tavernB.MaxTable);

            // Verify unchanged
            var tavernC = allTaverns.First(t => t.Id == 3);
            Assert.Equal("Tavern C", tavernC.TavernName);

            // Verify new inserts
            Assert.Contains(allTaverns, t => t.TavernName == "Tavern D");
            Assert.Contains(allTaverns, t => t.TavernName == "Tavern E");

            _output.WriteLine($"Complex BulkInsertOrUpdate scenario completed in {stopwatch.ElapsedMilliseconds}ms");
        }

        // Helper method to create a Tavern with all required properties
        private Tavern CreateTavern(string userId, string tavernName, string city, long id = 0)
        {
            return new Tavern
            {
                Id = id,
                UserId = userId,
                OwnerName = $"Owner of {tavernName}",
                CountryId = 1,
                Gender = "Not specified",
                TavernName = tavernName,
                StreetAddress = $"123 Main St",
                City = city,
                StateId = 1,
                ZipCode = "12345",
                LocationId = 100,
                County = $"County of {city}",
                Phone = "+1234567890",
                Fax = "+0987654321",
                WebsiteUrl = $"https://{tavernName.Replace(" ", "").ToLower()}.com",
                FirstName = "John",
                LastName = "Doe",
                UserName = userId,
                Password = "password123",
                Email = $"{userId}@test.com",
                CellPhone = "+1122334455",
                BigBrainFirstName = "Jane",
                BigBrainLastName = "Smith",
                BigBrainEmail = "bigbrain@test.com",
                BigBrainCell = "+9988776655",
                MaxTable = 30,
                FirstNight = "Monday",
                FirstNightTime1 = "18:00",
                FirstNightTime2 = "20:00",
                SecondNight = "Wednesday",
                SecondNightTime1 = "18:30",
                SecondNightTime2 = "20:30",
                CheckInTime = "17:00",
                RegistrationCloses = "19:00",
                RegistrationOpens = "16:00",
                MaxNumberOfTeams = 20,
                IsActive = true,
                TimeZone = "EST",
                Activity = DateTime.Now,
                NumberOfTimeUpdate = 0,
                OwnerId = 1,
                Notes = $"Notes for {tavernName}",
                AverageTeams = 15,
                BonusQuestions = 2,
                BirthDate = new DateTime(1980, 1, 1),
                PlayersPerTable = 6,
                BigBrainFirstName2 = "Bob",
                BigBrainEmail2 = "bob@test.com",
                BigBrainLastName2 = "Johnson",
                BigBrainCell2 = "+5544332211",
                WeeklyFirstPrize = "$100",
                WeeklySecondPrize = "$50",
                WeeklyThirdPrize = "$25",
                WeeklySpecials = "Happy Hour",
                TvVersion = false,
                ShippingAddress = "456 Ship St",
                ShippingCity = "Ship City",
                ShippingStateId = 2,
                ShippingZip = "54321",
                AutoGameMode = 0,
                FoodSpecial = "Wings",
                DrinkSpecial = "Beer",
                ChkOk = true
            };
        }
    }
}
