using Gurung.EfBulkOperations.SqlDataHandler;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Gurung.EfBulkOperations
{
    /// <summary>
    /// Represents configuration options for performing bulk data operations.
    /// </summary>
    /// <remarks>Use this class to specify settings such as batch size, identity preservation, locking
    /// behavior, and data handling when executing bulk insert or update operations. These options allow customization
    /// of performance, transactional behavior, and data mapping during bulk processing.</remarks>
    public class BulkConfig
    {
        /// <summary>
        /// Initializes a new instance of the BulkConfig class with default configuration settings.
        /// </summary>
        /// <remarks>The default values are: WithHoldlock is set to <see langword="true"/>, KeepIdentity
        /// is set to <see langword="false"/>, and BatchSize is set to 0. These defaults can be changed by setting the
        /// corresponding properties after instantiation.</remarks>
        public BulkConfig()
        {
            WithHoldlock = true;
            KeepIdentity = false;
            BatchSize = 0;
        }
        /// <summary>
        /// Gets or sets the number of items to process in each batch operation.
        /// </summary>
        public int BatchSize { get; set; } = 0;
        /// <summary>
        /// Gets or sets a value indicating whether the HOLDLOCK table hint is applied to queries.
        /// </summary>
        /// <remarks>When set to <see langword="true"/>, queries use the HOLDLOCK hint to hold shared
        /// locks until the end of the transaction, which can help prevent certain concurrency issues. Set to <see
        /// langword="false"/> to omit the HOLDLOCK hint. The default value is <see langword="true"/>.</remarks>
        public bool WithHoldlock { get; set; } = true;
        /// <summary>
        /// Gets or sets a value indicating whether to preserve identity values when inserting data.
        /// </summary>
        /// <remarks>Set this property to <see langword="true"/> to retain original identity values during data
        /// operations, such as bulk inserts. When set to <see langword="false"/>, new identity values may be generated by
        /// the database.</remarks>
        public bool KeepIdentity { get; set; } = false;
        /// <summary>
        /// Gets or sets the SQL data handler used to perform database operations.
        /// </summary>
        /// <remarks>Assign an implementation of ISqlDataHandler to customize how database interactions
        /// are handled. This property enables dependency injection for database access logic.</remarks>
        public ISqlDataHandler dataHandler { get; set; }
        /// <summary>
        /// Gets or sets the time, in seconds, before a bulk copy operation times out.
        /// </summary>
        /// <remarks>Set this property to control how long the bulk copy operation is allowed to run
        /// before being terminated. A value of 0 indicates no timeout, and the operation will wait indefinitely. Adjust
        /// this value based on expected data size and network conditions to avoid premature termination of long-running
        /// operations.</remarks>
        public int BulkCopyTimeout { get; set; }
        /// <summary>
        /// Gets or sets the number of operations to process before triggering a notification.
        /// </summary>
        /// <remarks>Set this property to control how frequently notifications are sent during batch
        /// processing. A value of 0 or less disables notifications.</remarks>
        public int NotifyAfter { get; set; }
    }
}
